import Header from '../components/Header.jsx'
import Footer from '../components/Footer.jsx'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 flex flex-col">
      <Header />
      <main className="flex-grow px-6 pt-32 pb-20">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
          <div className="prose prose-invert prose-emerald max-w-none text-gray-400 space-y-6">
            <p>
              By using AuditFast, you agree to these terms. Please read them carefully.
            </p>
            
            <h2 className="text-xl font-semibold text-white">1. Service Description</h2>
            <p>
              AuditFast provides AI-powered Conversion Rate Optimization (CRO) audits for landing pages. The service is provided "as is" and "as available" without any warranty of any kind.
            </p>

            <h2 className="text-xl font-semibold text-white">2. Use of Service</h2>
            <p>
              You may only submit URLs for which you have the right to request an audit. You agree not to use the service for any illegal or unauthorized purpose.
            </p>

            <h2 className="text-xl font-semibold text-white">3. Accuracy of Audits</h2>
            <p>
              Audits are generated by AI based on established CRO heuristics. While we strive for accuracy, the results are intended as suggestions and guidance, not as a guarantee of conversion improvement.
            </p>

            <h2 className="text-xl font-semibold text-white">4. Payments</h2>
            <p>
              Pro Audits are a one-time purchase. All payments are processed securely through Stripe. By purchasing a Pro Audit, you agree to Stripe's terms of service.
            </p>

            <h2 className="text-xl font-semibold text-white">5. Limitation of Liability</h2>
            <p>
              AuditFast and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.
            </p>

            <h2 className="text-xl font-semibold text-white">6. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Your continued use of the service after changes are posted constitutes your acceptance of the new terms.
            </p>

            <h2 className="text-xl font-semibold text-white">7. Contact</h2>
            <p>
              For any questions regarding these terms, please contact us at auditfast-2a99939f@ctomail.io.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
