export const blogPosts = [
  {
    slug: 'cro-checklist',
    title: 'Landing Page Audit Checklist: 20 CRO Issues That Kill Conversions',
    description: 'A 20-point CRO checklist covering above-the-fold, copy, trust, UX, and CTA. Find and fix the conversion killers on your landing page.',
    keywords: 'landing page audit, CRO audit, conversion rate optimization checklist',
    date: '2026-07-15',
  },
  {
    slug: 'cro-for-founders',
    title: 'Conversion Rate Optimization for Indie Founders: A Practical Guide',
    description: 'Practical CRO strategies for indie founders and small SaaS owners who can\'t afford a $2,500 consultant. Fix your landing page today.',
    keywords: 'conversion rate optimization, saas landing page tips, landing page optimization for founders',
    date: '2026-07-15',
  },
  {
    slug: 'cro-heuristics-guide',
    title: 'The Complete CRO Heuristics Guide: 33 Ways to Optimize Your Landing Page',
    description: 'All 33 CRO heuristics explained across 5 categories. Learn how professional consultants evaluate landing pages and improve your conversion rate.',
    keywords: 'CRO audit, CRO heuristics, conversion rate optimization',
    date: '2026-07-16',
  },
  {
    slug: '10-common-conversion-killers',
    title: '10 Common Conversion Killers (And How AuditFast Spots Them)',
    description: 'The 10 most common landing page mistakes that kill conversions. See if your site has them and how to fix them instantly.',
    keywords: 'conversion killers, CRO mistakes, landing page errors',
    date: '2026-07-16',
  },
  {
    slug: 'headline-formulas-that-convert',
    title: '5 Headline Formulas That Double Landing Page Conversions',
    description: '5 proven headline formulas that consistently outperform everything else. Tested against thousands of landing pages.',
    keywords: 'landing page headline formulas, CRO copywriting, conversion copywriting',
    date: '2026-07-17',
  },
  {
    slug: 'auditfast-vs-crazyegg',
    title: 'AuditFast vs CrazyEgg: Which Landing Page Tool is Better for Indie Founders?',
    description: 'Compare AuditFast\'s instant AI audit ($10 one-time) with CrazyEgg\'s heatmap tool ($29/mo). Which is right for your SaaS?',
    keywords: 'landing page audit tool, crazyegg alternative, CRO tools for startups',
    date: '2026-07-20',
  },
  {
    slug: 'free-cro-audit-tool',
    title: 'Free CRO Audit Tool: Why Every Founder Needs One Before Launching',
    description: 'Before you launch your landing page, run it through a free CRO audit tool. Learn why founders waste months on pages that don'\''t convert.',
    keywords: 'free cro audit tool, free landing page audit, AI landing page audit, CRO audit tool',
    date: '2026-07-24',
  },
  {
    slug: 'auditfast-vs-hotjar',
    title: 'AuditFast vs Hotjar: Which Landing Page Analysis Tool Is Right for You?',
    description: 'Compare AuditFast'\''s instant AI audit ($10 one-time) with Hotjar'\''s heatmaps and session recordings. Find out which fits your startup stage.',
    keywords: 'auditfast vs hotjar, hotjar alternative, landing page analysis tool, CRO software',
    date: '2026-07-24',
  },
  {
    slug: 'best-cro-audit-tools-2026',
    title: 'Best CRO Audit Tools for Indie Founders in 2026',
    description: 'Compare the top CRO audit tools for indie founders. Honest comparison of AuditFast, Hotjar, CrazyEgg, and more.',
    keywords: 'best cro audit tools, landing page optimization tools, CRO software for startups',
    date: '2026-07-24',
  },
  { slug: 'landing-page-audit-checklist-2026', title: 'Landing Page Audit Checklist: 15 Things to Fix Before You Launch', description: '15-point CRO audit checklist for landing pages. Fix hero clarity, CTAs, trust signals, and mobile UX before you launch.', keywords: 'landing page audit checklist, CRO checklist, conversion rate optimization checklist', date: '2026-07-25' },
  { slug: 'improve-landing-page-conversion-rate', title: 'How to Improve Landing Page Conversion Rate: A Founder's Guide', description: '7 proven ways to improve your landing page conversion rate. Fix headlines, CTAs, trust signals, mobile UX.', keywords: 'improve landing page conversion rate, landing page conversion tips, CRO guide', date: '2026-07-25' },
  { slug: 'saas-landing-page-optimization', title: 'SaaS Landing Page Optimization: 8 Changes That Move the Needle', description: '8 targeted changes that improve SaaS landing page conversions. No redesign needed.', keywords: 'saas landing page optimization, landing page conversion tips, SaaS CRO', date: '2026-07-25' },
  { slug: 'landing-page-ab-testing', title: 'Landing Page A/B Testing for Indie Founders', description: 'How to run landing page A/B tests on an indie budget. No expensive tools needed.', keywords: 'landing page AB testing, CRO testing for founders, free AB testing tools', date: '2026-07-25' },
];