export const blogPosts = [
  {
    slug: 'cro-checklist',
    title: 'Landing Page Audit Checklist: 20 CRO Issues That Kill Conversions',
    description: 'A 20-point CRO checklist covering above-the-fold, copy, trust, UX, and CTA. Find and fix the conversion killers on your landing page.',
    keywords: 'landing page audit, CRO audit, conversion rate optimization checklist',
    date: '2026-07-15',
  },
  {
    slug: 'cro-for-founders',
    title: 'Conversion Rate Optimization for Indie Founders: A Practical Guide',
    description: 'Practical CRO strategies for indie founders and small SaaS owners who can\'t afford a $2,500 consultant. Fix your landing page today.',
    keywords: 'conversion rate optimization, saas landing page tips, landing page optimization for founders',
    date: '2026-07-15',
  },
  {
    slug: 'cro-heuristics-guide',
    title: 'The Complete CRO Heuristics Guide: 33 Ways to Optimize Your Landing Page',
    description: 'All 33 CRO heuristics explained across 5 categories. Learn how professional consultants evaluate landing pages and improve your conversion rate.',
    keywords: 'CRO audit, CRO heuristics, conversion rate optimization',
    date: '2026-07-16',
  },
  {
    slug: '10-common-conversion-killers',
    title: '10 Common Conversion Killers (And How AuditFast Spots Them)',
    description: 'The 10 most common landing page mistakes that kill conversions. See if your site has them and how to fix them instantly.',
    keywords: 'conversion killers, CRO mistakes, landing page errors',
    date: '2026-07-16',
  },
  {
    slug: 'headline-formulas-that-convert',
    title: '5 Headline Formulas That Double Landing Page Conversions',
    description: '5 proven headline formulas that consistently outperform everything else. Tested against thousands of landing pages.',
    keywords: 'landing page headline formulas, CRO copywriting, conversion copywriting',
    date: '2026-07-17',
  },
  {
    slug: 'auditfast-vs-crazyegg',
    title: 'AuditFast vs CrazyEgg: Which Landing Page Tool is Better for Indie Founders?',
    description: 'Compare AuditFast\'s instant AI audit ($10 one-time) with CrazyEgg\'s heatmap tool ($29/mo). Which is right for your SaaS?',
    keywords: 'landing page audit tool, crazyegg alternative, CRO tools for startups',
    date: '2026-07-20',
  },
  {
    slug: 'free-cro-audit-tool',
    title: 'Free CRO Audit Tool: Why Every Founder Needs One Before Launching',
    description: 'Before you launch your landing page, run it through a free CRO audit tool. Learn why founders waste months on pages that don'\''t convert.',
    keywords: 'free cro audit tool, free landing page audit, AI landing page audit, CRO audit tool',
    date: '2026-07-24',
  },
  {
    slug: 'auditfast-vs-hotjar',
    title: 'AuditFast vs Hotjar: Which Landing Page Analysis Tool Is Right for You?',
    description: 'Compare AuditFast'\''s instant AI audit ($10 one-time) with Hotjar'\''s heatmaps and session recordings. Find out which fits your startup stage.',
    keywords: 'auditfast vs hotjar, hotjar alternative, landing page analysis tool, CRO software',
    date: '2026-07-24',
  },
  {
    slug: 'best-cro-audit-tools-2026',
    title: 'Best CRO Audit Tools for Indie Founders in 2026',
    description: 'Compare the top CRO audit tools for indie founders. Honest comparison of AuditFast, Hotjar, CrazyEgg, and more.',
    keywords: 'best cro audit tools, landing page optimization tools, CRO software for startups',
    date: '2026-07-24',
  },
  { slug: 'landing-page-audit-checklist-2026', title: 'Landing Page Audit Checklist: 15 Things to Fix Before You Launch', description: '15-point CRO audit checklist for landing pages. Fix hero clarity, CTAs, trust signals, and mobile UX before you launch.', keywords: 'landing page audit checklist, CRO checklist, conversion rate optimization checklist', date: '2026-07-25' },
  { slug: 'improve-landing-page-conversion-rate', title: 'How to Improve Landing Page Conversion Rate: A Founder's Guide', description: '7 proven ways to improve your landing page conversion rate. Fix headlines, CTAs, trust signals, mobile UX.', keywords: 'improve landing page conversion rate, landing page conversion tips, CRO guide', date: '2026-07-25' },
  { slug: 'saas-landing-page-optimization', title: 'SaaS Landing Page Optimization: 8 Changes That Move the Needle', description: '8 targeted changes that improve SaaS landing page conversions. No redesign needed.', keywords: 'saas landing page optimization, landing page conversion tips, SaaS CRO', date: '2026-07-25' },
  { slug: 'landing-page-ab-testing', title: 'Landing Page A/B Testing for Indie Founders', description: 'How to run landing page A/B tests on an indie budget. No expensive tools needed.', keywords: 'landing page AB testing, CRO testing for founders, free AB testing tools', date: '2026-07-25' },
  { slug: 'landing-page-best-practices-2026', title: 'Landing Page Best Practices for 2026', description: 'What actually converts on landing pages in 2026. Real patterns from real pages.', keywords: 'landing page best practices 2026, what converts, landing page tips', date: '2026-07-26' },
  { slug: 'social-proof-landing-pages', title: 'Social Proof on Landing Pages: What Actually Builds Trust', description: 'Which types of testimonials, logos, and numbers actually move the needle.', keywords: 'social proof landing pages, landing page trust signals, testimonials', date: '2026-07-26' },
  { slug: 'landing-page-copywriting-tips', title: 'Landing Page Copywriting: 7 Rules That Convert', description: 'Landing page copywriting rules for headlines, body copy, and CTAs that actually work.', keywords: 'landing page copywriting, conversion copy tips, CTA copy', date: '2026-07-26' },
  { slug: 'reduce-landing-page-bounce-rate', title: 'How to Reduce Landing Page Bounce Rate', description: '6 landing page fixes that keep visitors on your page and push them toward conversion.', keywords: 'reduce bounce rate, landing page bounce rate fix, keep visitors on page', date: '2026-07-26' },
  { slug: 'hero-section-optimization', title: 'Hero Section Optimization: 5 Rules for Above-the-Fold', description: 'Your hero section has 3 seconds. These 5 rules make every pixel earn its place.', keywords: 'hero section optimization, above the fold CRO, landing page hero', date: '2026-07-26' },
  { slug: 'cta-button-optimization', title: 'CTA Button Optimization: 4 Decisions That Affect Click-Through', description: 'CTA button text, color, placement, and surrounding copy all affect conversions.', keywords: 'CTA button optimization, call to action, CTA click through rate', date: '2026-07-26' },
  { slug: 'cro-for-early-stage-startups', title: 'CRO for Early-Stage Startups: When to Start Optimizing', description: 'When early-stage startups should invest in CRO and what to fix first.', keywords: 'early stage CRO, startup conversion optimization, when to start CRO', date: '2026-07-26' },
];